language: generic
sudo: required

services:
  - docker
before_install:
  - docker build -t deerajreddy9/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true deerajreddy9/react-test npm test

after_success:
  - docker build -t deerajreddy9/multi-client ./client
  - docker build -t deerajreddy9/multi-worker ./worker
  - docker build -t deerajreddy9/multi-server ./server
  - docker build -t deerajreddy9/multi-nginx ./nginx
  # login to docker hub & pull image
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  - docker push deerajreddy9/multi-client
  - docker push deerajreddy9/multi-worker
  - docker push deerajreddy9/multi-server
  - docker push deerajreddy9/multi-nginx